language: go

go:
  - "1.16"

addons:
  apt:
    chrome: stable

env:
  global:
    - GOLANG_VERSION="${TRAVIS_GO_VERSION}"
    - APP_VERSION="${TRAVIS_TAG:-edge}"

before_install:
  - export CHROMEDP_TEST_RUNNER=google-chrome-stable
  - export CHROMEDP_DISABLE_GPU=true
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make get
  - go get github.com/mattn/goveralls

script:
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out
  - make GOLANG_VERSION="${GOLANG_VERSION%.x}" APP_VERSION="${APP_VERSION##*(v)}" image

after_success:
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out

notifications:
  email: true