language: go

go:
  - "1.16"

addons:
  apt:
    chrome: stable

env:
  global:
    - GOLANG_VERSION="${TRAVIS_GO_VERSION}"
    - MIM_VERSION="${TRAVIS_TAG:-development}"

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make get
  - go get github.com/mattn/goveralls

script:
  - export CHROMEDP_TEST_RUNNER=google-chrome-stable
  - export CHROMEDP_DISABLE_GPU=true
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out
  - docker build --pull --cache-from "$DOCKER_IMAGE:latest" --build-arg GOLANG_VERSION="${GOLANG_VERSION%.x}" --build-arg LIBVIPS_VERSION="${LIBVIPS}" --build-arg MIM_VERSION="${MIM_VERSION}" --tag "$DOCKER_IMAGE:${MIM_VERSION}" --tag "$DOCKER_IMAGE:latest" -f docker/Dockerfile .
  - docker push "$DOCKER_IMAGE:${MIM_VERSION}"
  - docker push "$DOCKER_IMAGE:latest"

notifications:
  email: true