name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16-alpine
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install chrome
        run: |
          apk update && apk upgrade && apk add --no-cache bash git build-base chromium
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit tests
        run: |
          export CHROMEDP_DISABLE_GPU=true
          go test -race -covermode atomic -coverprofile=covprofile ./...
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: covprofile
